apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service-pod
  template:
    metadata:
      labels:
        app: node-service-pod
    spec:
      containers:
        - name: node-service
          image: localhost:5000/node-img
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6700
---
# nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service-pod
  template:
    metadata:
      labels:
        app: node-service-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-node
spec:
  selector:
    app: node-service-pod
  ports:
    - name: nginx
      port: 80
      targetPort: 80
    - name: app
      port: 4000
      targetPort: 6700
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # enable non root url service mapping
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    name: myingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: service-node
                port:
                  number: 80
          - pathType: Prefix
            path: "/app/test"
            backend:
              service:
                name: service-node
                port:
                  number: 4000
